### ISSUE TITLE
httpx dependency is httpx<0.22 in 0.0.3 release

### ISSUE THREAD

**Issue by antont** [sensodevices/async-sendgrid#1]
Hi, thanks for sharing the lib!

Somehow the 0.0.3 release is depending on old httpx:
`async-sendgrid 0.0.3 depends on httpx<0.22 and >=0.21`

I'm now depending on the latest git version, instead of pypi, and that allowed me to install async-sendgrid with current httpx.

`async-sendgrid @ git+https://github.com/sensodevices/async-sendgrid@2832ccb6c06e1ed7faeaa1476ab5214d59ee9c6a
`
> Successfully installed async-sendgrid-0.0.0 h11-0.14.0 httpcore-0.17.2 httpx-0.24.1

**Comment by Actticus** [comment]
Sorry for a long fix @antont
